// src/constants/nhlLogos.js
export const nhlLogos = {
    ANA: "/images/nhl-logos/ANA.webp",
    BOS: "/images/nhl-logos/BOS.webp",
    BUF: "/images/nhl-logos/BUF.webp",
    CAL: "/images/nhl-logos/CAL.webp",
    CHI: "/images/nhl-logos/CHI.webp",
    DAL: "/images/nhl-logos/DAL.webp",
    DET: "/images/nhl-logos/DET.webp",
    EDM: "/images/nhl-logos/EDM.webp",
    FLA: "/images/nhl-logos/FLA.webp",
    HFD: "/images/nhl-logos/HFD.webp",
    LAK: "/images/nhl-logos/LAK.webp",
    MTL: "/images/nhl-logos/MTL.webp",
    NJD: "/images/nhl-logos/NJD.webp",
    NYI: "/images/nhl-logos/NYI.webp",
    NYR: "/images/nhl-logos/NYR.webp",
    OTT: "/images/nhl-logos/OTT.webp",
    PHL: "/images/nhl-logos/PHL.webp",
    PIT: "/images/nhl-logos/PIT.webp",
    QUE: "/images/nhl-logos/QUE.webp",
    SJS: "/images/nhl-logos/SJS.webp",
    STL: "/images/nhl-logos/STL.webp",
    TBL: "/images/nhl-logos/TBL.webp",
    TOR: "/images/nhl-logos/TOR.webp",
    VAN: "/images/nhl-logos/VAN.webp",
    WAS: "/images/nhl-logos/WAS.webp",
    WPG: "/images/nhl-logos/WPG.webp"
  };
  